### ISSUE TITLE
Data structure for Priority Barriers list/table

### ISSUE THREAD

**Issue by nickw-CWF** [Canadian-Wildlife-Federation/Horsefly-WCRP#27]
I am adding fields to ``priority_barriers.csv`` to account for the different data structure. Below is the complete data structure we want to display in the dashboard table when 'Priority Barriers' is selected, some of these fields will come from the csv while some will be pulled from the ``crossings`` table (I have noted the source for each field in the table). You'll have to join the ``priority_barriers.csv`` to the ``crossings`` table based on ``aggregated_crossings_id``, and then select the fields below for display in the table.

| field | aggregated_crossings_id | stream_name | road_name | owner | proposed_fix | estimated_cost | upstr_hab_quality | barrier_type | hab_gain | cost_benefit_ratio | priority | next_steps | reason | notes |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| display name | Barrier ID | Stream Name | Road Name | Owner | Proposed Fix | Estimated Cost ($k) | Upstream Habitat Quality | Barrier Type | Habitat Gain (km) | Cost-Benefit Ratio ($k/km) | Priority | Next Steps | Reason | Notes |
| source | bcfishpass.crossings/csv | csv | csv | csv | csv | csv | csv | csv | bcfishpass.crossings[all_spawningrearing_belowupstrbarriers_km] | calculation = estimated_cost/hab_gain | csv | csv | csv | csv |

Would setting up the table in this way conflict with any of the interactive functionality between table and map?

**Comment by TomasMillaKoch** [comment]
The tables the way it is set up would not affect the code in place but, the code will have to be changed to show the csv in the way above as the data table.

**Comment by TomasMillaKoch** [comment]
The table might work if we append the csv columns to the geojson turned datatable in dash.

**Comment by nickw-CWF** [comment]
Done.
